# Generated by Django 5.1.1 on 2024-09-12 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='default_value',
            field=models.CharField(blank=True, choices=[('Kun', 'Kun'), ('Tun', 'Tun')], default='Kun', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='defect_measure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.material'),
        ),
        migrations.AlterField(
            model_name='report',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.product'),
        ),
        migrations.AlterField(
            model_name='report',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='termoplast_measure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='waste_measure',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
