# Generated by Django 5.1.1 on 2024-09-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_report_default_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='edit_msg',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
