# Generated by Django 5.1.1 on 2024-09-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_tguser_edit_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='machine_num',
            field=models.IntegerField(default=1, max_length=2, verbose_name='aparat'),
            preserve_default=False,
        ),
    ]
