# Generated by Django 5.1.1 on 2024-09-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_report_machine_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='machine_num',
            field=models.IntegerField(blank=True, max_length=2, null=True, verbose_name='aparat'),
        ),
    ]
