# Generated by Django 5.1.1 on 2024-09-16 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_alter_report_machine_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material', to='bot.product'),
        ),
    ]
