# Generated by Django 5.1.1 on 2024-09-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_alter_material_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='product',
        ),
        migrations.AddField(
            model_name='material',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='materials', to='bot.product'),
        ),
    ]
