# Generated by Django 5.1.1 on 2024-09-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_remove_material_product_material_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
