# Generated by Django 5.1.1 on 2024-09-19 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_report_is_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='is_finished',
        ),
    ]
