# Generated by Django 5.1.1 on 2024-09-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_report_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='defect_measure',
            field=models.FloatField(blank=True, null=True, verbose_name='brak'),
        ),
        migrations.AlterField(
            model_name='report',
            name='machine_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='aparat'),
        ),
        migrations.AlterField(
            model_name='report',
            name='waste_measure',
            field=models.FloatField(blank=True, null=True, verbose_name='atxod'),
        ),
    ]
