# Generated by Django 5.1.1 on 2024-09-21 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_alter_report_defect_measure_alter_report_machine_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='defect_measure',
            field=models.FloatField(blank=True, null=True, verbose_name='atxod'),
        ),
        migrations.AlterField(
            model_name='report',
            name='waste_measure',
            field=models.FloatField(blank=True, null=True, verbose_name='brak'),
        ),
    ]
