# Generated by Django 5.1.1 on 2024-09-21 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produkt', to='bot.product'),
        ),
    ]
