# Generated by Django 5.1.1 on 2024-09-24 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_machine_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine', to='bot.product'),
        ),
    ]
